GET DATA
  /TYPE=TXT
  /FILE="/home/burkhard/Entwicklung/Apfel/iters.txt"
  /ARRANGEMENT=DELIMITED
  /DELCASE=LINE
  /FIRSTCASE=2
  /DELIMITERS=";"
  /QUALIFIER='"'
  /VARIABLES=
    iters F3.0.

EXAMINE 
	/VARIABLES= iters
	/STATISTICS = DESCRIPTIVES
	/PERCENTILES
	/PLOT = BOXPLOT HISTOGRAM NPPLOT
	/COMPARE = GROUPS
	/MISSING=LISTWISE.
